# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Daman_QGIS
                                 A QGIS plugin
 Комплексный инструмент для работы с данными в QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-01-29
        copyright            : (C) 2025 by Author
        email                : email@example.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from qgis.gui import QgisInterface
    from .main_plugin import DamanQGIS as DamanQGISType


# noinspection PyPep8Naming
def classFactory(iface: "QgisInterface") -> "DamanQGISType":  # pylint: disable=invalid-name
    """Load Daman_QGIS class from file main_plugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .main_plugin import DamanQGIS
    return DamanQGIS(iface)
